export const GET_LATEST_RATES_REQUESTED = 'GET_LATEST_RATES_REQUESTED';
export const GET_LATEST_RATES_SUCCEDED = 'GET_LATEST_RATES_SUCCEDED';
export const GET_LATEST_RATES_FAILED = 'GET_LATEST_RATES_FAILED';

export const ADD_BASE = 'ADD_RATE';
